"""new filed in  followers  model

Revision ID: 663aab1c9d22
Revises: 7f007bcc812a
Create Date: 2021-07-28 17:28:40.429957

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '663aab1c9d22'
down_revision = '7f007bcc812a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
                    sa.Column('follower_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
